language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust:
        - beta

  include:
    # Mac builds
    # - env: TARGET=i686-apple-darwin
    #   os: osx
    # - env: TARGET=x86_64-apple-darwin
    #   os: osx

    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master

before_script:
  - git config --global user.name "Travis bot"

script: |
  cargo build --verbose --all &&
  cargo test --verbose --all

notifications:
  email: false
  webhooks:
    urls: https://webhooks.gitter.im/e/365ee5abbaba33b8f6d6
    on_success: change
    on_failure: always
    on_start: never
