language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable

branches:
  only:
    - master

before_script:
  - git config --global user.name "Travis bot"

script: |
  cargo build --verbose --all &&
  cargo test --verbose --all

notifications:
  email: false
  webhooks:
    urls: https://webhooks.gitter.im/e/365ee5abbaba33b8f6d6
    on_success: change
    on_failure: always
    on_start: never
