[package]
name = "rdbg_core"
version = "0.1.0"

[lib]
name = "rdbg_core"

[dependencies]
simplelog = "^0.4.2"
log = "0.3.8"
fnv = "1.0.3"
nix = { git = "https://github.com/nix-rust/nix", branch = "master" }
libc = { git = "https://github.com/rust-lang/libc", branch = "master" }
